name: Run Ansible Playbook

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out the repository code
      - name: Check out code
        uses: actions/checkout@v4

      # 2. Set up the SSH key from a GitHub Secret
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # 3. Add target host to known_hosts to avoid interactive prompts
      - name: Add target to known_hosts
        run: ssh-keyscan -p 1234 -H 127.0.0.1 >> ~/.ssh/known_hosts

      # 4. Run the Ansible playbook
      - name: Run Ansible Playbook
        run: |
          pip install ansible
          ansible-playbook -i inventory.ini playbook.yml
